CREATE TABLE IF NOT EXISTS misiones (
	id INT AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(150) NOT NULL,
	descripcion TEXT NULL,
	orden INT NOT NULL DEFAULT 0,
	estado ENUM('activa', 'inactiva') NOT NULL DEFAULT 'activa',
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	KEY idx_misiones_estado (estado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
